version: '3'
services:
  pyenv:
    build:
      context: ./project
      shm_size: "4gb"
    command:
      "sleep infinity"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./project:/project
      - ./log:/log
    network_mode: "host"

