
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-24T16:58:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "099730713e702de1db57ede5171a1c6cf9b88735",
 "version": "0.15.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
