
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T20:51:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "635347a127a3292c05272da6be059a6100cbe472",
 "version": "2022.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
