name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 install pytest
      - name: Lint with flake8
        run: |
          cd project
          flake8 . --count --show-source --statistics
      - name: Install dependencies
        run: |
          pip install ./project
          mkdir /log
      - name: Test with pytest
        run: |
          pytest
