# Workflow for build sphinx html/pdf to documents branch
name: Docs

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOC_BRANCH: __docs__

jobs:
  build-sphinx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64
      - name: Git configuration
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
          git checkout -B $DOC_BRANCH
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install mermaid
        run: npm install -g @mermaid-js/mermaid-cli
      - name: Install sphinx
        run: |
          python -m pip install --upgrade pip
          pip install ./project
          pip install sphinx sphinx_rtd_theme myst-parser nbsphinx sphinxcontrib-mermaid
          sudo apt-get update && sudo apt-get -y install pandoc latexmk texlive-lang-japanese texlive-latex-extra
      - name: build sphinx
        run: |
          sphinx-apidoc -e -f -o ./docs ./project/package
          cd ./docs
          make html
          make latexpdf
      - name: move dirs
        run: |
          mv docs/ __docs__/
          cp -rp __docs__/_build/html  docs/
          cp -rp __docs__/_build/latex pdf/
      - name: Commit and push to documents branch
        run: |
          git add --all
          git commit -m "update docs"
          git push --force -u origin $DOC_BRANCH
