# Workflow for build sphinx html/pdf to documents branch
name: Docs

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOC_BRANCH: documents

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64
      - name: Git configuration
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install mermaid
        run: npm install -g @mermaid-js/mermaid-cli
      - name: Install sphinx
        run: |
          python -m pip install --upgrade pip
          pip install ./project
          pip install sphinx sphinx_rtd_theme myst-parser nbsphinx sphinxcontrib-mermaid
          sudo apt-get update && sudo apt-get -y install pandoc latexmk texlive-lang-japanese texlive-latex-extra
      - name: Run apidoc
        run: |
          sphinx-apidoc -e -f -o ./docs ./project/package
          cd ./docs
          make html
          make latexpdf
      - name: Check if there is any new translations
        id: verify_diff
        run: |
          git diff --quiet || echo "::set-output name=new_translations_exist::true"
      - name: Commit and push to documents branch
        if: steps.verify_diff.outputs.new_translations_exist == 'true'
        run: |
          git checkout $DOC_BRANCH 2>/dev/null || git checkout -b $DOC_BRANCH
          git commit -am "update documents"
          git push
