name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install black isort
      - name: Git configuration
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
      - name: Format
        run: |
          cd project
          isort --check-only --diff . || isort -v .
          black --check --diff . || black -v .
          git commit -am "[actions] stylefix"
          git push
